# This image depends on a UT licensed RedHat installation exported from a Vagrant image and produces that same image
# registered to our RHN Satellite server.
FROM ut-rhel6

MAINTAINER Rick Huff <rhuff@austin.utexas.edu>

# Register with the RH Satellite server.
RUN /rhn_reg.sh

# CMD /bin/bash
